import "../../stylesheet/TransactionHistory.scss"

export default function TransactionHistory() {
  return (
    <div id="transaction-history-container">
      <h1>Transaction History</h1>
      <table>
        <thead>
          <tr>
            <th>title1</th>
            <th>title2</th>
            <th>title3</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>item</td>
            <td>item</td>
            <td>item</td>
          </tr>
          <tr>
            <td>item</td>
            <td>item</td>
            <td>item</td>
          </tr>
          <tr>
            <td>item</td>
            <td>item</td>
            <td>item</td>
          </tr>
          <tr>
            <td>item</td>
            <td>item</td>
            <td>item</td>
          </tr>
          <tr>
            <td>item</td>
            <td>item</td>
            <td>item</td>
          </tr>
          <tr>
            <td>item</td>
            <td>item</td>
            <td>item</td>
          </tr>
          <tr>
            <td>item</td>
            <td>item</td>
            <td>item</td>
          </tr>
          <tr>
            <td>item</td>
            <td>item</td>
            <td>item</td>
          </tr>
          <tr>
            <td>item</td>
            <td>item</td>
            <td>item</td>
          </tr>
          <tr>
            <td>item</td>
            <td>item</td>
            <td>item</td>
          </tr>
          <tr>
            <td>item</td>
            <td>item</td>
            <td>item</td>
          </tr>
          <tr>
            <td>item</td>
            <td>item</td>
            <td>item</td>
          </tr>
          <tr>
            <td>item</td>
            <td>item</td>
            <td>item</td>
          </tr>
          <tr>
            <td>item</td>
            <td>item</td>
            <td>item</td>
          </tr>
          <tr>
            <td>item</td>
            <td>item</td>
            <td>item</td>
          </tr>
          <tr>
            <td>item</td>
            <td>item</td>
            <td>item</td>
          </tr>
          <tr>
            <td>item</td>
            <td>item</td>
            <td>item</td>
          </tr>
          <tr>
            <td>item</td>
            <td>item</td>
            <td>item</td>
          </tr>
          <tr>
            <td>item</td>
            <td>item</td>
            <td>item</td>
          </tr>
          <tr>
            <td>item</td>
            <td>item</td>
            <td>item</td>
          </tr>
          <tr>
            <td>item</td>
            <td>item</td>
            <td>item</td>
          </tr>
          <tr>
            <td>item</td>
            <td>item</td>
            <td>item</td>
          </tr>
          <tr>
            <td>item</td>
            <td>item</td>
            <td>item</td>
          </tr>
        </tbody>
      </table>
    </div>
  )
}